default_platform(:android)

platform :android do
 desc "Deploy beta version to the Google Play"
  lane :beta do
          increment_version_code(gradle_file_path: "app/build.gradle")
          gradle(task: "clean bundleRelease")
          upload_to_play_store(track: 'beta')
     end
end
