default_platform(:android)

platform :android do
  desc "add version code"
     lane :bump_version_code do
         path = '../app/build.gradle'
         re = /versionCode\s+(\d+)/
         s = File.read(path)
         versionCode = s[re, 1].to_i
         s[re, 1] = (versionCode + 1).to_s
         f = File.new(path, 'w')
         f.write(s)
         f.close
     end
  desc "Deploy a beta version to the Google Play"
     lane :beta do
         gradle(task: "clean bundleRelease")
         upload_to_play_store(track: 'beta')
     end
end

